---
- name: try
  hosts: all

  tasks:
    - name: Get uptime information
      ansible.builtin.shell: | 
        echo "I am user with uid $(whoami) logged on to server $(hostname) which has been up since $(uptime)"
        echo "Currently there $(who | wc -l) users logged in and here's what they are doing \n `ps -u | awk {'print $1, $3, $4, $11'}`"
      register: result_of_uptime

    - name: Print uptime
      debug:
        msg: "{{ result_of_uptime.stdout_lines }}"
@